app:
  name: manager-service
  host: 127.0.0.1
  grpc_port: 50000
  http_port: 8000
  
database:
  host: 10.43.238.190
  port: 5432
  username: postgres
  password: 123456
  name: sale-tickets

jwt-key: 1111-2222-3333-4444-5555-6666